name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  arg1:  # id of input
    description: 'arg1'
    required: true
    default: 'default1'
  arg2:  # id of input
    description: 'arg2'
    required: true
    default: 'default2'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.arg1 }}
    - ${{ inputs.arg2 }}